/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: {
      responses: {
        /** OK */
        200: unknown
      }
    }
  }
  '/url_redirects': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.url_redirects.id']
          created_at?: parameters['rowFilter.url_redirects.created_at']
          updated_at?: parameters['rowFilter.url_redirects.updated_at']
          from?: parameters['rowFilter.url_redirects.from']
          to?: parameters['rowFilter.url_redirects.to']
          user_id?: parameters['rowFilter.url_redirects.user_id']
          /** Filtering Columns */
          select?: parameters['select']
          /** Ordering */
          order?: parameters['order']
          /** Limiting and Pagination */
          offset?: parameters['offset']
          /** Limiting and Pagination */
          limit?: parameters['limit']
        }
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range']
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit']
          /** Preference */
          Prefer?: parameters['preferCount']
        }
      }
      responses: {
        /** OK */
        200: {
          schema: definitions['url_redirects'][]
        }
        /** Partial Content */
        206: unknown
      }
    }
    post: {
      parameters: {
        body: {
          /** url_redirects */
          url_redirects?: definitions['url_redirects']
        }
        query: {
          /** Filtering Columns */
          select?: parameters['select']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** Created */
        201: unknown
      }
    }
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.url_redirects.id']
          created_at?: parameters['rowFilter.url_redirects.created_at']
          updated_at?: parameters['rowFilter.url_redirects.updated_at']
          from?: parameters['rowFilter.url_redirects.from']
          to?: parameters['rowFilter.url_redirects.to']
          user_id?: parameters['rowFilter.url_redirects.user_id']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.url_redirects.id']
          created_at?: parameters['rowFilter.url_redirects.created_at']
          updated_at?: parameters['rowFilter.url_redirects.updated_at']
          from?: parameters['rowFilter.url_redirects.from']
          to?: parameters['rowFilter.url_redirects.to']
          user_id?: parameters['rowFilter.url_redirects.user_id']
        }
        body: {
          /** url_redirects */
          url_redirects?: definitions['url_redirects']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
  }
}

export interface definitions {
  url_redirects: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number
    created_at?: string
    updated_at?: string
    from: string
    to: string
    user_id: string
  }
}

export interface parameters {
  /** Preference */
  preferParams: 'params=single-object'
  /** Preference */
  preferReturn: 'return=representation' | 'return=minimal' | 'return=none'
  /** Preference */
  preferCount: 'count=none'
  /** Filtering Columns */
  select: string
  /** On Conflict */
  on_conflict: string
  /** Ordering */
  order: string
  /** Limiting and Pagination */
  range: string
  /** Limiting and Pagination */
  rangeUnit: string
  /** Limiting and Pagination */
  offset: string
  /** Limiting and Pagination */
  limit: string
  /** url_redirects */
  'body.url_redirects': definitions['url_redirects']
  'rowFilter.url_redirects.id': string
  'rowFilter.url_redirects.created_at': string
  'rowFilter.url_redirects.updated_at': string
  'rowFilter.url_redirects.from': string
  'rowFilter.url_redirects.to': string
  'rowFilter.url_redirects.user_id': string
}

export interface operations {}

export interface external {}
